import os

env = os.getenv('APP_ENV', 'development')

if env == 'production':
    from .production import ProductionConfig as Config
else:
    from .development import DevelopmentConfig as Config

FLASK_HOST = Config.FLASK_HOST
FLASK_PORT = Config.FLASK_PORT
FLASK_DEBUG = Config.FLASK_DEBUG
SECRET_KEY = Config.SECRET_KEY

LLM_API_KEY = Config.LLM_API_KEY
LLM_BASE_URL = Config.LLM_BASE_URL
LLM_MODEL_NAME = Config.LLM_MODEL_NAME
ZEP_API_KEY = Config.ZEP_API_KEY

DEFAULT_MAX_ROUNDS = Config.DEFAULT_MAX_ROUNDS
DEFAULT_MINUTES_PER_ROUND = Config.DEFAULT_MINUTES_PER_ROUND
DEFAULT_ACTIVE_AGENTS_MIN = Config.DEFAULT_ACTIVE_AGENTS_MIN
DEFAULT_ACTIVE_AGENTS_MAX = Config.DEFAULT_ACTIVE_AGENTS_MAX

UPLOAD_FOLDER = Config.UPLOAD_FOLDER
MAX_CONTENT_LENGTH = Config.MAX_CONTENT_LENGTH

SQLALCHEMY_DATABASE_URI = Config.SQLALCHEMY_DATABASE_URI
SQLALCHEMY_TRACK_MODIFICATIONS = Config.SQLALCHEMY_TRACK_MODIFICATIONS

CORS_ORIGINS = Config.CORS_ORIGINS
CORS_SUPPORTS_CREDENTIALS = Config.CORS_SUPPORTS_CREDENTIALS
CORS_METHODS = Config.CORS_METHODS
CORS_ALLOW_HEADERS = Config.CORS_ALLOW_HEADERS
